### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by chancity** [justcoding121/Titanium-Web-Proxy#122]
I haven't been able to locate the problem code, but there seems to be a deadlock of some sort with https traffic after the proxy server has been running for 30 minutes or so.  I have to manually restart the server. Is this a known issue?

**Comment by justcoding121** [comment]
No. Which version are you using?

**Comment by ilushka85** [comment]
This is solved in my latest commit... its just locking from semaphore lock.  I have rewritten the cert generator to use certenroll and switch to a concurrent dictionary for caching.  This is much faster and does not access the cert store.

**Comment by chancity** [comment]
@ilushka85 I'll try it out, thanks.

**Comment by chancity** [comment]
@ilushka85 I'm not sure if this is working or not because this now creates the certificate different than the last versions.  All my users are already using a certificate generated by the last version and I haven't been able to replicate a certificate that is usable in your newest iteration.

**Comment by chancity** [comment]
It also seems to be creating a new root cert every time it's ran

**Comment by ilushka85** [comment]
It does indeed create certificates differently then before.  Is the only issue that it will not honor the previous root certificate?  If that is the case I can add some code to check for old root and use it, otherwise generate new root and store it locally as opposed to the cert store(this is expensive).

**Comment by chancity** [comment]
Yes that is the only issue, thanks :D

**Comment by chancity** [comment]
@ilushka85 The new CertEnroll is also creating multiple certificates in my "Intermediate Certification Authorities"

**Comment by ilushka85** [comment]
My latest commit saves and loads the root cert from the local directory for a cert named:  rootCert.pfx


You can place your existing one there to preserve it.  Otherwise it will generate a new one and save to this file and load it from the file if the file exists.



What do you mean by certenroll is creating multiple certificates in the intermediate certifcation authorities?

**Comment by chancity** [comment]
Key not valid for use in specified state is the error I'm receiving when trying to use my previously generated certificate.

**Comment by chancity** [comment]
I was forgot to use my .pfx password when opening it and now I'm getting this error. 

@ilushka85 

Exception has been thrown by the target of an invocation.
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   at Titanium.Web.Proxy.Network.CertEnrollEngine.GenerateCertificate(Boolean IsRoot, String SubjectCN, String FullSubject, Int32 PrivateKeyLength, String HashAlg, DateTime ValidFrom, DateTime ValidTo, X509Certificate2 SigningCertificate) in C:\Users\Chancey\Desktop\Titanium-Web-Proxy-releasev2\Titanium.Web.Proxy\Network\CertEnrollEngine.cs:line 151
   at Titanium.Web.Proxy.Network.CertEnrollEngine.InternalCreateCert(String sSubjectCN, Boolean isRoot, Boolean switchToMTAIfNeeded, X509Certificate2 signingCert) in C:\Users\Chancey\Desktop\Titanium-Web-Proxy-releasev2\Titanium.Web.Proxy\Network\CertEnrollEngine.cs:line 223

**Comment by chancity** [comment]
Could you just use the objects directly instead of invoking them? I think that would make the CertEnroll class less confusing...I started to do it.  I'll post it when I'm done.

**Comment by ilushka85** [comment]
Just pushed fixes for this issue.  You will need to resave the pfx before running.

**Comment by justcoding121** [comment]
Should be fixed in beta
