### ISSUE TITLE
ProxyServer#Stop is broken

### ISSUE THREAD

**Issue by Wintereise** [justcoding121/Titanium-Web-Proxy#321]
Test code:

```
var proxy = new ProxyServer();
proxy.AddEndPoint(new ExplicitProxyEndPoint(IPAddress.Parse("127.0.0.1"), 6100, false));
proxy.Start();
proxy.Stop();
```

Expected result: Proxy is started (this works fine), and then stopped gracefully.

Actual result:

```
Unhandled Exception: info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
      Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.<>c.<AcceptTcpClientAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Titanium.Web.Proxy.ProxyServer.<Listen>d__141.MoveNext() in C:\projects\titanium-web-proxy\Titanium.Web.Proxy\ProxyServer.cs:line 701
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

This is possibly related to #107, anyone have any clues?

**Comment by Wintereise** [comment]
In providing further details, I'm calling it from a ASP.NET core MVC controller. I've got my own persistence layer to make the object stick around as a singleton (via the container), that works fine.

However, trying to stop in any circumstance from a controller seems to throw this error, even if you created the `ProxyServer` in the same request.

The method that handles this invocation is very simple:

```
        [HttpGet("{name}/{task}", Name = "ManageServices")]
        public IEnumerable<string> Manage (string name, string task)
        {
            Logger.LogDebug("Service manager n -> " + name + ", a -> " + task);

            if (validServices.Any(s => name == s) &&
                validActions.Any(s => task == s))
            {

                var proxy = new ProxyServer();
                proxy.AddEndPoint(new ExplicitProxyEndPoint(IPAddress.Parse("127.0.0.1"), 6100, false));
                proxy.Start();
                proxy.Stop();
                return new string[] { name + " was " + task + "ed successfully" };
            }
            else
               throw new EInvalidRequest();   
        }
```

**Comment by Wintereise** [comment]
@honfika I can confirm that https://github.com/justcoding121/Titanium-Web-Proxy/commit/8182416aae8a8e75dfd950e02285c03984d3539f fixes this.

Issue can probably be closed, thoughts?
