### ISSUE TITLE
Crash on trying to listen on ip:port pairs that are unavailable (for any reason)

### ISSUE THREAD

**Issue by Wintereise** [justcoding121/Titanium-Web-Proxy#342]
`Listen` on ProxyServer.cs has no error handling when attempting to start the listener, this might fail for a multitude of reasons. When it does, the whole runtime dies due to the unhandled exception

```
        private void Listen(ProxyEndPoint endPoint)
        {
            endPoint.Listener = new TcpListener(endPoint.IpAddress, endPoint.Port);
            endPoint.Listener.Start(); <-- Problem occurs here.

            endPoint.Port = ((IPEndPoint)endPoint.Listener.LocalEndpoint).Port;
            // accept clients asynchronously
            endPoint.Listener.BeginAcceptTcpClient(OnAcceptConnection, endPoint);
        }
```

Issue:
```
System.Net.Sockets.SocketException: Cannot assign requested address
at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at System.Net.Sockets.TcpListener.Start(Int32 backlog)
at System.Net.Sockets.TcpListener.Start()
at Titanium.Web.Proxy.ProxyServer.d__141.MoveNext() in G:\Spectero\proxy\Titanium.Web.Proxy\ProxyServer.cs:line 691
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

My proposed fix:
```
        private void Listen(ProxyEndPoint endPoint)
        {
            endPoint.Listener = new TcpListener(endPoint.IpAddress, endPoint.Port);
            try
            {
                endPoint.Listener.Start();
                endPoint.Port = ((IPEndPoint)endPoint.Listener.LocalEndpoint).Port;
                // accept clients asynchronously
                endPoint.Listener.BeginAcceptTcpClient(OnAcceptConnection, endPoint);
            }
            catch (SocketException e)
            {
                ExceptionFunc(new Exception("Attempt to start a listener on (" + endPoint.IpAddress + ":" + endPoint.Port + ") failed. " + e.Message, e));
            }
        }
```

The entire error object is enhanced and passed in as an inner exception. The user can now deal with it however they want.

Thoughts @honfika @justcoding121 ?

**Comment by honfika** [comment]
Why don't you put the `proxyServer.Start()` to a try-catch?
For me it seems that `ExceptionFunc` is for the exceptions thrown in the background threads.

I think it would be misleading if we swallow the exception on proxy start. The users will debug their code, everything seems to work with the starting, but the proxy is not working. I'd hate that behavior:)

**Comment by Wintereise** [comment]
Hi, mostly, because it lacks information on which exact endpoint failed.

Could rethrow it after dressing it up, thoughts? @honfika 

```
System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at Titanium.Web.Proxy.ProxyServer.Listen(ProxyEndPoint endPoint) in G:\Spectero\proxy\Titanium.Web.Proxy\ProxyServer.cs:line 649
   at Titanium.Web.Proxy.ProxyServer.Start() in G:\Spectero\proxy\Titanium.Web.Proxy\ProxyServer.cs:line 562
   at Tester.Program.Main(String[] args) in G:\Spectero\daemon\Tester\Program.cs:line 27
```

**Comment by honfika** [comment]
What do you think about this?
```
        private void Listen(ProxyEndPoint endPoint)
        {
            endPoint.Listener = new TcpListener(endPoint.IpAddress, endPoint.Port);
            try
            {
                endPoint.Listener.Start();

                endPoint.Port = ((IPEndPoint)endPoint.Listener.LocalEndpoint).Port;

                // accept clients asynchronously
                endPoint.Listener.BeginAcceptTcpClient(OnAcceptConnection, endPoint);
            }
            catch (SocketException ex)
            {
                var pex = new Exception($"Endpoint {endPoint} failed to start. Check inner exception and exception data for details.", ex);
                pex.Data.Add("ipAddress", endPoint.IpAddress);
                pex.Data.Add("port", endPoint.Port);
                throw pex;
            }
        }

```

**Comment by Wintereise** [comment]
@honfika That looks great, and will work for my needs. Will wait for you to commit.

**Comment by honfika** [comment]
Beta nuget package was released some hours ago.

**Comment by honfika** [comment]
Stable version was released, too.
I close this issue now, feel free to reopen it/create new issue if you have any problem.
