### ISSUE TITLE
HTTP CONNECT handling is broken for Transparent Proxy

### ISSUE THREAD

**Issue by dracool** [justcoding121/Titanium-Web-Proxy#401]
Project that reproduces the issue for me:
https://github.com/dracool/TitanumIssue339Reproduction

- The latest working version is **3.0.277-beta**
- Reproduction tested with version **3.0.392-beta** (StreamExtended **1.0.141-beta**) as well as with version built from current source

**expected result:**
- endless loop of forwarding to 127.0.0.1:11388/

**actual result:**
````
System.Net.Http.HttpRequestException: An error occurred while sending the request. --->
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. --->
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Issue339Reproduction.Program.<Main>d__0.MoveNext() in .\Issue339Reproduction\Program.cs:line 27
````

**environment:**
- OS: Windows 10 Version 1709 Build 16299.125 (Fall Creators Update)
- .Net 4.7.1
- C# Version 7.2
- Visual Studio 2017 Community

**Comment by honfika** [comment]
Are you sure that it should work with IP address? If you use hostname and the certificate is trusted, then it works for me.

**Comment by honfika** [comment]
And of course you have to trust the certificate. Either manuall or with the 
`            proxy.CertificateManager.EnsureRootCertificate(true);
`call.

**Comment by dracool** [comment]
Indeed changing both of these things seems to be a workaround, but it doesn't solve the underlying issue(s).

---
Why is it necessary that the root certificate be trusted? It was entirely intentionally to leave the certificate untrusted. I'm aware of the security issues of using untrusted certificates, but those certificates would only be trusted on the host machine anyway.

I tried adding the call `proxy.CertificateManager.EnsureRootCertificate(false);` which I assumed would create an entirely untrusted root certificate, but it doesn't seem to set a certificate at all; this is the exception thrown by Titanium Web Proxy:

````
System.Exception: Could'nt authenticate client 'localhost' with fake certificate. --->
System.ArgumentNullException: Value cannot be null.
Parameter name: serverCertificate
   at System.Net.Security.SslState.ValidateCreateContext(Boolean isServer, String targetHost, SslProtocols enabledSslProtocols, X509Certificate serverCertificate, X509CertificateCollection clientCertificates, Boolean remoteCertRequired, Boolean checkCertRevocationStatus, Boolean checkCertName)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Titanium.Web.Proxy.ProxyServer.<HandleClient>d__134.MoveNext()
   --- End of inner exception stack trace ---
````

I'm not sure how this would be fixed, but if this case is not support supported it should probably throw an exception before a client tries to connect.

----

IP addresses should be valid common names or at least alternate subject names in certificates, requests made against an IP address are accepted but return no headers or data to the client. There is no exception generated at all in Titanium Web Proxy. Even if this use case won't be supported it should generate an appropriate error both for the client (status 500) and the proxy (exception).

----

Thanks for your hard work on this project. Sadly I don't have the time to get familiar with the code at the moment, so I can't make any pull requests in the next weeks.

**Comment by honfika** [comment]
Whaere did you add the 
`proxy.CertificateManager.EnsureRootCertificate(false);`
call?

I added it after the `AddEndpoint` line, and I receive:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Issue339Reproduction.Program.<Main>d__0.MoveNext() in C:\Titanium\TitanumIssue339Reproduction\Issue339Reproduction\Program.cs:line 21

```
So I can't reproduce the ArgumentNullException.

Trusting the root certificate on the proxyserver machine is not needed. You have to trust it on the client machine. But in your example it is the same.

Instead of trusting the certificate you can ignore the errors on client side:
```
                using (var handler = new WebRequestHandler())
                {
                    handler.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;
                    using (var client = new HttpClient(handler))
                    {
                        // this also errors out for Insomnia, it is not specific to the demonstration used here
                        var result = await client.GetAsync("https://localhost:11388/");
                    }
                }

```
It needs adding a reference to System.Net.Http.WebRequest assembly.

But since now the proxy calls itself, you need to ignore it on the proxy side, too:
```
            proxy.ServerCertificateValidationCallback += Proxy_ServerCertificateValidationCallback;

        private async Task Proxy_ServerCertificateValidationCallback(object sender, CertificateValidationEventArgs e)
        {
            e.IsValid = true;
        }
```

But I think this is not a normal usage. Normally you have to trust the certificate on the client only. And it solves the ip address problem, too.

**Comment by honfika** [comment]
When I'm sending the reuqest from chrome to 127.0.0.1, it sends the following clienthello:

Version: 3.3 (TLS/1.2)
Random: 1B 3B 7E 0C 27 64 E1 92 E4 EF 02 F4 F7 89 C2 25 ED A9 C8 9F 69 D4 E4 3A 04 6D DE A9 92 0C 84 23
"Time": 1976. 08. 23. 0:00:59
SessionID: 51 73 50 40 AD D3 03 8F 26 88 93 EA E4 04 8B E2 1B D9 59 6B 6C 1C 63 15 A6 43 61 8E 2C E5 B1 EB
Extensions:
renegotiation_info: 00
extended_master_secret: 
SessionTicket TLS: 
signature_algorithms: sha256_ecdsa, Intrinsic_Unknown[0x04], sha256_rsa, sha384_ecdsa, Intrinsic_Unknown[0x05], sha384_rsa, Intrinsic_Unknown[0x06], sha512_rsa, sha1_rsa
status_request: OCSP - Implicit Responder
signed_certificate_timestamp: 
ALPN: h2, http/1.1
channel_id: 
ec_point_formats: uncompressed [0x0]
unknown_33: 00 29 3A 3A 00 01 00 00 1D 00 20 E6 FF 4E CC 5C B5 2C 77 D7 D0 24 4A 76 3E FE 9D C9 2C 96 AE 2E B4 5A CD 2B 4B 54 0D F3 14 7D 14
psk_key_exchange_modes: 01 01
supported_versions: 0A 2A 2A 7F 17 03 03 03 02 03 01
supported_groups: unknown [0x3A3A], x25519 [0x1D], secp256r1 [0x17], secp384r1 [0x18]
Reserved (GREASE): 00
padding: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Compression: null
Ciphers:
[0x1A1A] unknown
[0x1301] unknown
[0x1302] unknown
[0x1303] unknown
[0xC02B] TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
[0xC02F] TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[0xC02C] TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
[0xC030] TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[0xCCA9] TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
[0xCCA8] TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
[0xC013] TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
[0xC014] TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
[0x009C] TLS_RSA_WITH_AES_128_GCM_SHA256
[0x009D] TLS_RSA_WITH_AES_256_GCM_SHA384
[0x002F] TLS_RSA_WITH_AES_128_CBC_SHA
[0x0035] TLS_RSA_WITH_AES_256_CBC_SHA
[0x000A] TLS_RSA_WITH_3DES_EDE_CBC_SHA

It does not contain the IP address:(

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen if needed.
