### ISSUE TITLE
getting NullReferenceException when trying to service http request internally

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#432]
I'm using a http proxy and trying to respond directly to the client with the code below.

I'm seeing NREs which seem to correspond to the proxy trying to close a non-existing server connection.

Any tips? 

thanks

```
        private async Task OnBeforeRequest(object sender, SessionEventArgs e) {
            var uri = e.WebSession.Request.RequestUri;
            if (uri.Host == "dummy.local") {
                e.Ok("<!DOCTYPE html>" +
                      "<html><body><h1>" +
                      "Website Blocked" +
                      "</h1>" +
                      "<p>Blocked by titanium web proxy.</p>" +
                      "</body>" +
                      "</html>");
        }
    }

Exception: ProxyHttpException: Error occured whilst handling session response
   at Titanium.Web.Proxy.ProxyServer.<HandleHttpSessionResponse>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Titanium.Web.Proxy.ProxyServer.<HandleHttpSessionRequest>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<HandleHttpSessionRequest>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Titanium.Web.Proxy.ProxyServer.<HandleClient>d__2.MoveNext()

Inner Exception: NullReferenceException: Object reference not set to an instance of an object.
   at Titanium.Web.Proxy.EventArguments.SessionEventArgs.GetStreamReader(Boolean isRequest)
   at Titanium.Web.Proxy.EventArguments.SessionEventArgs.<CopyBodyAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Titanium.Web.Proxy.EventArguments.SessionEventArgs.<SyphonOutBodyAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Titanium.Web.Proxy.ProxyServer.<HandleHttpSessionResponse>d__149.MoveNext()
```

**Comment by jgilbert2017** [comment]
looks like the offending code is `SessionEventArgs.GetStreamReader` which dereferences `WebSession.ServerConnection` which is null.
