### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#434]
I get this weird error occasionally on some sites. Not sure anything to do with connection cache. But lets track this until we get more information. For example

> Could'nt authenticate client www.google.com with fake certificate.

**Comment by justcoding121** [comment]
Got some more details in one case. Not sure why I haven't noticed it before, may be just what it says.

> {System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
>    at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
>    at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
>    at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
>    at Titanium.Web.Proxy.Extensions.SslExtensions.AuthenticateAsServerAsync(SslStream sslStream, SslServerAuthenticationOptions options, CancellationToken token) in C:\Work\Repositories\Titanium-Web-Proxy\Titanium.Web.Proxy\Extensions\SslExtensions.cs:line 75
>    at Titanium.Web.Proxy.ProxyServer.<handleClient>d__2.MoveNext() in C:\Work\Repositories\Titanium-Web-Proxy\Titanium.Web.Proxy\ExplicitClientHandler.cs:line 176}
