### ISSUE TITLE
Titanium not working with Mobile Gmail Apps

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#511]
Hello,
         I created a Web proxy using Titanium.Web.Proxy (transparent proxy) in my network. I connected my Iphone to the network using VPN.  I have installed the rootCert.cer file on my phone browse https sites on my Iphone.
I can also see the logs of the sites accessed in Titanium Proxy. 
However whenever I try to use my Gmail App or Google Drive App , it fails to sync.
On Titanium I do see lot of exceptions thrown :- 

```
Could'nt authenticate client 'inbox.google.com' with fake certificate.
   at Titanium.Web.Proxy.ProxyServer.<handleClient>d__185.MoveNext()
```

and also 

```
 Error occured whilst handling session request
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                         ification(Task task)
   at Titanium.Web.Proxy.ProxyServer.<handleClient>d__185.MoveNext()
```

Could you please suggest how to solve this issue. 
I am on latest Titanium build (dotnet core) and its running on Ubuntu machine with BouncyCastle CertificateEngine.

**Comment by judebigj** [comment]
Thats what I thought,  Thanks.
