### ISSUE TITLE
Error in handling request on first client connection

### ISSUE THREAD

**Issue by skazemi** [justcoding121/Titanium-Web-Proxy#560]
Hello,
I used titanium to build a cache server as a class library, referenced my class library in a project in the same solution which worked well. when I copy the "bin" folder of my class library (including titanium and its dependencies) to use it in a separate solution (without using nuget packages) the following error raises on first client request:

Error occured whilst handling session request

   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Titanium.Web.Proxy.ProxyServer.<handleClient>d__2.MoveNext()

**Comment by skazemi** [comment]
Resolved the issue by looking `First Chance Exceptions` in the new project. The `original exception` was a `load error` about `BrotliSharp` which was updated to a newer version. The `exception handling mechanism` in the following lines is **_HIDING_** the probable `exceptions` to be `raised and reported properly`. I think at least the original exception should be logged in console for convenient debugging.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/d4a6d2bae8a50f4c39e1c15ad16e2282861f5745/src/Titanium.Web.Proxy/RequestHandler.cs#L260

**Comment by justcoding121** [comment]
I Would think in this case the exception be wrapped inside ProxyHttpException as inner exception.

ProxyException => InnerException => InnerException

So are you saying its missing the inner exception?

**Comment by honfika** [comment]
Issue closed, feel free to reopen it if you still need it.
