### ISSUE TITLE
Timeouting request

### ISSUE THREAD

**Issue by arabcewicz** [justcoding121/Titanium-Web-Proxy#599]
When getting to https://cctr.med.kyushu-u.ac.jp/redcap/ through TitaniumWebProxy, one of the requests - to https://cctr.med.kyushu-u.ac.jp/redcap/redcap_v8.10.11/Resources/js/base.js  timeouts. It can be reproduced using the WPF demo application within the project - see marked exception:
![screen](https://user-images.githubusercontent.com/9028835/60672717-5cb1da80-9e76-11e9-9148-1947177ad994.png)
The full stack trace of the exception is
```
Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request ---> System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__182.MoveNext()
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Titanium.Web.Proxy.ProxyServer.<handleClient>d__2.MoveNext()
```

What's interesting, when I pass the traffic through the additional local proxy (Fiddler) adding the appropriate `proxyServer.UpStreamHttpsProxy = ...` everything works fine.

Please fix this.

**Comment by arabcewicz** [comment]
It looks like the problem lies inside `StreamExtended` dependency - upgrading it from 1.0.188-beta to 1.0.201 resolved the issue.
So please, publish officially a new nuget package with the newest version of the library.

**Comment by honfika** [comment]
In the later version StreamExtended package won't be required for Titanium, because it was copied to the Titanium repository.

**Comment by honfika** [comment]
Please try the latest beta package (3.1.1015 or newer).

**Comment by arabcewicz** [comment]
Sorry for the late response.
Just checked with 3.1.1021 and it works without changing `proxy.BufferSize`. Thanks a lot!
