### ISSUE TITLE
Getting exception while using Transparent Proxy.

### ISSUE THREAD

**Issue by harrip12** [justcoding121/Titanium-Web-Proxy#620]
Hello,
       I am using Transparent Proxy, while processing the HTTPs requests I am getting Exception. Following is Stack trace:

> Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request ---> System.Exception: A client is making HTTP request to one of the listening ports of this proxy stackoverflow.com:12001
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, IPEndPoint upStreamEndPoint, ExternalProxy externalProxy, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, IPEndPoint upStreamEndPoint, ExternalProxy externalProxy, Boolean noCache, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.Release(Task1 connectionCreateTask, Boolean closeServerConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, TcpClientConnection clientConnection, CustomBufferedStream clientStream, HttpResponseWriter clientStreamWriter, CancellationTokenSource cancellationTokenSource, String httpsConnectHostname, ConnectRequest connectRequest, Task1 prefetchConnectionTask)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, TcpClientConnection clientConnection, CustomBufferedStream clientStream, HttpResponseWriter clientStreamWriter, CancellationTokenSource cancellationTokenSource, String httpsConnectHostname, ConnectRequest connectRequest, Task1 prefetchConnectionTask)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, TcpClientConnection clientConnection, CustomBufferedStream clientStream, HttpResponseWriter clientStreamWriter, CancellationTokenSource cancellationTokenSource, String httpsConnectHostname, ConnectRequest connectRequest, Task1 prefetchConnectionTask)

Please help me out

**Comment by honfika** [comment]
Which TWP version? Is this a new problem in v3.1?

**Comment by harrip12** [comment]
I am using TWP v3.0 and earlier I was using Extended Proxy, Yesterday I changed it to Transparent Proxy.

**Comment by harrip12** [comment]
I also tried with v3.1, same exception occurred.

**Comment by ByronAP** [comment]
have you tried disabling connection prefetch?

**Comment by honfika** [comment]
Please try the latest version.

**Comment by honfika** [comment]
Closing this issue due to inactivity. Feel free to reopen if needed.
