### ISSUE TITLE
Cant load certificate as a service

### ISSUE THREAD

**Issue by yuvalpikel** [justcoding121/Titanium-Web-Proxy#738]
Hi 
I am using the Web Proxy as a service to decrypt https
but i am getting this error : 
[1/23/2020 12:57:28 PM]Unhandled Exception in ProxyServer, Exception = System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights. ---> System.Security.Cryptography.CryptographicException: The request is not supported.

   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
[1/23/2020 12:57:28 PM]Unhandled Exception in ProxyServer, Exception = System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights. ---> System.Security.Cryptography.CryptographicException: The request is not supported.

   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---

How can i fix it ?

**Comment by honfika** [comment]
does your service has an admin right?

1st solution is to give them admin
2nd: trust the certificate manually

**Comment by yuvalpikel** [comment]
Thanks ,
1. My service run as a local system , is that enough?
2. How can it be achieved (Sorry ,  i am not familiar with it)

**Comment by honfika** [comment]
1: I thought it is enough, but I never tried to run in a service... maybe somebody else can answer.

2: https://success.outsystems.com/Support/Enterprise_Customers/Installation/Install_a_trusted_root_CA__or_self-signed_certificate

**Comment by sideup66** [comment]
Hi,
I ran into this problem myself experimenting wih a service. In my application, its going to need to have the cert pre installed as i do not think it will be good user design to ask the user every time the proxy starts....easiest way to clear this is to install the cert into your root certificate folder as the computer account, then launch your proxy. When it does the user certificate check, even if the certificate is not installed, it will not matter, as it is registered to the system, which supercedes any user configured settings.

**Comment by yuvalpikel** [comment]
Thanks man.. I will try it
Have you used any special methods with  the proxy in order to work as a
service?

**Comment by yuvalpikel** [comment]
![image](https://user-images.githubusercontent.com/32258434/73606315-9932e980-45b1-11ea-8a05-8592cfc62b42.png)

After i've loaded the root certificate it is still not working .. 
Can you look at the image to make sure i did it right ?

**Comment by sideup66** [comment]
Hi, yes, looks like your cert is in the right place. Sorry for late reply. I have not been able to run it as a service so far. let me know if you have any development

**Comment by nkochnev** [comment]
I have started windows service via my domain account. 
It's bad decision, but it works

**Comment by justcoding121** [comment]
Closing this as a Windows service/certificate-store setup issue. A service should not try to install a root into its CurrentUser store at runtime. Install the root certificate into LocalMachine\Root during an elevated installer/deployment step, load the matching PFX in the service, and construct ProxyServer without requesting user-store trust. Client machines or accounts that use the proxy must also trust the same root. Running the service as a domain user only changes which CurrentUser store is addressed; it is not the preferred deployment fix.
