### ISSUE TITLE
AuthenticationException when running proxy inside IIS

### ISSUE THREAD

**Issue by enkelmedia** [justcoding121/Titanium-Web-Proxy#859]
I have a .NET 5 app hosted inside IIS, I'm using Selenium to perform fetch information from websites and use the Titanium Proxy to intercept the requests.

It all works fine on my dev-machine but on Windows 2019 server we're getting errors like this:

```
Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'accounts.google.com' with certificate '*.google.com'.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
```

We've tried to figure out what's wrong but without any luck. It feels related to certificates and/or user permissions. It's interesting that when we tried to set the App Pool identity to "Administrator" it worked, but not when using AppPoolIdentity or NetworkService.

Any ideas?

**Comment by justcoding121** [comment]
Closing this as an IIS identity/private-key configuration issue. The fact that an Administrator app-pool identity works points to the worker account lacking access to the generated certificate private key or certificate/cache location. Pre-create the root/PFX, grant the app-pool identity read access to its private key and write access to the certificate cache, and enable Load User Profile if CurrentUser storage is used. Do not run the pool as Administrator. For a long-lived network proxy, a dedicated Windows service is generally a better host than IIS.
