### ISSUE TITLE
 Unhandled Exception in ProxyServer, Couldn't authenticate host 'play.google.com' with certificate '*.google.com'

### ISSUE THREAD

**Issue by Elanchezhiyan-AIT** [justcoding121/Titanium-Web-Proxy#948]
Hi Team, 

whenever I debug, I'm getting this error. Could you please guide me to fix this issue?

_Unhandled Exception in ProxyServer, Exception = Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'play.google.com' with certificate '*.google.com'. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Titanium.Web.Proxy.ProxyServer.<handleClient>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.<handleClient>d__0.MoveNext()_

**Comment by Elanchezhiyan-AIT** [comment]
@honfika , Do we have any updates on this?

**Comment by justcoding121** [comment]
﻿Leaving open — this is a client-facing TLS authenticate-as-server failure, not a duplicate of other TLS reports.

We do not have a current net10.0 reproduction from the original stack trace (SslState.EndProcessAuthentication / transport closed). To act on this we need a fresh capture against current develop:

1. The full exception including InnerException (and any InnerException.InnerException)
2. CertificateEngine (BouncyCastle / BouncyCastleFast / Windows)
3. Whether the client trusts the proxy root, and the leaf subject/SAN for the failing host
4. OS / .NET version

Please comment with that when you can; until then there is nothing actionable to fix here.

**Comment by justcoding121** [comment]
Leaving closed — separate from #890.

We could not reproduce a current net10.0 failure for authenticating play.google.com with a generated '*.google.com' leaf through ExplicitProxyEndpoint (DecryptSsl=true) on develop. The stack in the report is from older SslState/FromAsync paths.

Please reopen/update with:
1. Titanium.Web.Proxy package or commit SHA
2. Target framework (ideally net10.0)
3. Full exception including InnerException (and any ExceptionStatus / SslPolicyErrors)
4. Whether the system root CA for the proxy was trusted by the client process
5. A minimal repro if it still fails against play.google.com today

Without that, this looks like a client abort/trust issue rather than a proxy cert-generation bug we can act on.
